@hostname = localhost
@portDev = 3000
@hostDev = {{hostname}}:{{portDev}}
@contentType = application/json

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMzU2Y2ZlNDEzMTM1NWM1NWQ4ZGNjYiIsImlhdCI6MTc4MTg4NjIwNiwiZXhwIjoxNzgxODkzNDA2fQ.mFXaAE6w5TwgfMHyoed1_6oC6sh82e6KzO75ypFyYwg

### LOCAL: get users - Obtener usuarios
GET http://{{hostDev}}/api/auth/users HTTP/1.1
content-type: {{contentType}}
Authorization: Bearer {{token}}





