@hostname = localhost
@portDev = 3000
@hostDev = {{hostname}}:{{portDev}}
@contentType = application/json

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMzU5ZGRjZjI5MjA4MmRhOTk2MmJmYyIsImlhdCI6MTc4MjE1MDMzNiwiZXhwIjoxNzgyMTU3NTM2fQ.WeyFKsMgGExXHPlfCYVcMeItUFdkO4isOD4b93KYjMI

### LOCAL: get users - Obtener usuarios
GET http://{{hostDev}}/api/auth/users HTTP/1.1
content-type: {{contentType}}
Authorization: Bearer {{token}}





