@hostname = localhost
@portDev = 3000
@hostDev = {{hostname}}:{{portDev}}
@contentType = application/json


### LOCAL: register - Registrar usuario
POST http://{{hostDev}}/api/auth/register HTTP/1.1
content-type: {{contentType}}

{
    "name": "Jesus",
    "email": "jesus@example.com",
    "password": "password957314"
}





